
REDIS_URL = 'redis://localhost'
REIDS_HOST = 'localhost'
REIDS_PORT = 6379

REDIS_RFAB_GLOBAL_KEY_PREFIX = 'rfab'

REDIS_OM_PLANT_MODEL_KEY_PREFIX = 'plant'

REDIS_JBOD_STAT_KEY_PREFIX = f'{REDIS_RFAB_GLOBAL_KEY_PREFIX}:jbodstat'
REDIS_DUT_INFO_KEY_PREFIX = f'{REDIS_RFAB_GLOBAL_KEY_PREFIX}:dutinfo'

REDIS_PLANT_UPDATE_CH_PREFIX = f'{REDIS_RFAB_GLOBAL_KEY_PREFIX}:update'
REDIS_ACTION_CH_PREFIX = f'{REDIS_RFAB_GLOBAL_KEY_PREFIX}:action'

REDIS_LOG_CH_NAME = f'{REDIS_RFAB_GLOBAL_KEY_PREFIX}:log'
REDIS_ERROR_CH_NAME = f'{REDIS_RFAB_GLOBAL_KEY_PREFIX}:err'
